######################################################################
# Automatically generated by qmake (2.01a) dim. sept. 30 12:29:40 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . Include Src
INCLUDEPATH += . Include

# Input
HEADERS += Include/enums.h Include/mainwindow.h Include/scene_area.h
SOURCES += Src/main.cpp Src/mainwindow.cpp Src/scene_area.cpp
RESOURCES += MainWindow.qrc
