#ifndef ENUMS
#define ENUMS

enum toolsID {
	TOOLS_ID_FREEHAND,
	TOOLS_ID_LINE,
	TOOLS_ID_RECTANGLE,
	TOOLS_ID_CIRCLE,
	TOOLS_ID_POLYGON,
	TOOLS_ID_TEXT
};
enum penStylesID {
	DOTS_PEN,
	SOLIDE_PEN
};
enum penWidthID{
	SMALL_PEN,
	MEDIUM_PEN,
	LARGE_PEN
};
enum menusID{
	FILE_MENU_ID_NEW,
	FILE_MENU_ID_OPEN,
	FILE_MENU_ID_SAVE,
	FILE_MENU_ID_SAVE_AS,
	TOOLS_MENU_ID_FREEHAND,
	TOOLS_MENU_ID_LINE,
	TOOLS_MENU_ID_CIRCLE,
	TOOLS_MENU_ID_RECTANGLE,
	TOOLS_MENU_ID_POLYGON,
	TOOLS_MENU_ID_TEXT,
	STYLE_MENU_ID_PEN,
	STYLE_MENU_ID_BRUSH,
	STYLE_MENU_ID_FONT
};

enum brushStyle{
	NO_BRUSH,
	SOLIDE_PATTERN,
	DENSE_PATTERN

};
#endif
